sudo: false
language: python
python:
  - "2.7"
  - "3.6"
cache: pip
env:
  - TOX_ENV=py27-flake8
  - TOX_ENV=py27-docs
  - TOX_ENV=py36-django2.0-drf3.7 DATABASE_URL=sqlite://
  - TOX_ENV=py36-django2.0-drf3.7 DATABASE_URL=mysql://root:@localhost/test_db
  - TOX_ENV=py36-django2.0-drf3.7 DATABASE_URL=postgres://postgres@/test_db
matrix:
  fast_finish: true
install:
  - pip install -r requirements.txt
  - pip install tox python-coveralls psycopg2 mysqlclient
script:
  - tox -e $TOX_ENV
  - coverage run runtests.py
after_success:
  coveralls
deploy:
  provider: pypi
  user: avelis
  password:
    secure: lHfvDnLiTBDJzps3BNYQ1+RoNdusLhy+ua2ikDurvRgM58hbzDgy/R0MhpFPW9hWMSpXQ6bx75T6BYjfl+daY2nvJ6/l4vx5NsynOnPa8v2LdwPMr2QylmZRFsklIn6iV7/KDm3JbODPUytAyg/PBrfnPRDZIdUlE1vf4s8/I79hSoT9r+Afg+i5F8ZUoRX01Gxh4xbSo9tJA3UbjyBAnx4D0/U3RA0EaSXdH+H1OaCVeaF6l8bRY3gf+RSuGusLMaSynVmhNZLRrPzRJgf0kkFMk6xhlWGPEmscRU/whv/1MSchdq4lUKsrt38Ay2RrLTgHnya4w7PFa24xNhlOfmLzM5yjVFZIkDt+A2afU8u3fAkI1gIdYAIp/ICc5L0CBCVGXddljpug3FiPXlMY9x9C7uSI5Z4vEPQncBrI/rbgGj7YbvQDjR4LzRL+FJgg7X+yklHuSgF45DN5YDtO0xnspms1z5FccPjvczusX0eUEd7aYjKD4fOEsjdxoi9oMw+jmDjEVH4xg2pRuqR6lVW4WYpfjsPUbURa2R6dIwxZ6gdIRqJN8nYnG/DrvQoqkZg53CiHdWlP0BuPTnXuCjGlsx7o/sHhErysuOSsvufUhlQTOqFofAOdU/0h8Yxa4SL3jV3fqHIDrmkbVFcTKIXwiEAEkBtMe/8qD2ooPGs=
  distributions: "sdist bdist_wheel"
on:
    tags: true
    repo: aschn/drf-tracking
